# Generated by Django 5.1.3 on 2024-11-20 15:45

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_deposits'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=main.models.generate_unique_name),
        ),
    ]
