import self
from django.core.management import BaseCommand

from main.models import Customer


class Command(BaseCommand):
    def handle(self, *args, **options):
        customers = [{"first_name":"Carol","last_name":"Lopes","email":"clopes0@mac.com","gender":"Female","weight":71,"dob":"2001-11-22"},
{"first_name":"Christiano","last_name":"Cuvley","email":"ccuvley1@sitemeter.com","gender":"Male","weight":98,"dob":"2004-05-08"},
{"first_name":"Courtnay","last_name":"Boutell","email":"cboutell2@sun.com","gender":"Female","weight":43,"dob":"2000-06-01"},
{"first_name":"Salome","last_name":"Madrell","email":"smadrell3@yolasite.com","gender":"Female","weight":99,"dob":"2003-03-24"},
{"first_name":"Corrina","last_name":"Dufaur","email":"cdufaur4@tamu.edu","gender":"Female","weight":47,"dob":"2001-07-23"},
{"first_name":"Demetris","last_name":"Josskoviz","email":"djosskoviz5@phoca.cz","gender":"Male","weight":57,"dob":"2003-08-27"},
{"first_name":"Jolie","last_name":"Dobey","email":"jdobey6@com.com","gender":"Female","weight":71,"dob":"1999-08-25"},
{"first_name":"Paloma","last_name":"Alenin","email":"palenin7@google.ca","gender":"Female","weight":56,"dob":"2002-03-24"},
{"first_name":"Brenna","last_name":"Kleinhaus","email":"bkleinhaus8@timesonline.co.uk","gender":"Female","weight":66,"dob":"1999-10-11"},
{"first_name":"Waylin","last_name":"Packington","email":"wpackington9@gnu.org","gender":"Male","weight":88,"dob":"2004-07-17"},
{"first_name":"Walliw","last_name":"Meadowcraft","email":"wmeadowcrafta@multiply.com","gender":"Female","weight":97,"dob":"2004-09-27"},
{"first_name":"Darren","last_name":"Glamart","email":"dglamartb@rakuten.co.jp","gender":"Male","weight":37,"dob":"2003-07-25"},
{"first_name":"Glennis","last_name":"McGivena","email":"gmcgivenac@europa.eu","gender":"Female","weight":82,"dob":"2005-11-26"},
{"first_name":"Osgood","last_name":"Beall","email":"obealld@ihg.com","gender":"Male","weight":91,"dob":"2000-08-23"},
{"first_name":"Cynthea","last_name":"Manuel","email":"cmanuele@domainmarket.com","gender":"Female","weight":99,"dob":"2003-09-27"},
{"first_name":"Lillis","last_name":"Blabie","email":"lblabief@clickbank.net","gender":"Female","weight":97,"dob":"1998-07-27"},
{"first_name":"Blaine","last_name":"Weblin","email":"bwebling@europa.eu","gender":"Male","weight":56,"dob":"2004-11-07"},
{"first_name":"Nickie","last_name":"Duckering","email":"nduckeringh@edublogs.org","gender":"Female","weight":59,"dob":"2004-01-16"},
{"first_name":"Baily","last_name":"Biggam","email":"bbiggami@geocities.jp","gender":"Male","weight":71,"dob":"2005-02-28"},
{"first_name":"Hurlee","last_name":"Austwick","email":"haustwickj@homestead.com","gender":"Male","weight":88,"dob":"2002-01-22"},
{"first_name":"Bennett","last_name":"Attrill","email":"battrillk@dailymail.co.uk","gender":"Male","weight":59,"dob":"1998-07-24"},
{"first_name":"Sidonia","last_name":"Guesford","email":"sguesfordl@bloglovin.com","gender":"Female","weight":61,"dob":"2000-12-04"},
{"first_name":"Jyoti","last_name":"Bastie","email":"jbastiem@4shared.com","gender":"Female","weight":45,"dob":"2002-02-12"},
{"first_name":"Valentine","last_name":"Sedgmond","email":"vsedgmondn@huffingtonpost.com","gender":"Male","weight":60,"dob":"2001-01-23"},
{"first_name":"Brittani","last_name":"Le Gassick","email":"blegassicko@addtoany.com","gender":"Female","weight":61,"dob":"2004-09-13"},
{"first_name":"Alexandr","last_name":"Schindler","email":"aschindlerp@i2i.jp","gender":"Male","weight":64,"dob":"1999-08-15"},
{"first_name":"Abel","last_name":"Desaur","email":"adesaurq@huffingtonpost.com","gender":"Male","weight":54,"dob":"2001-01-22"},
{"first_name":"Rodolfo","last_name":"Van Schafflaer","email":"rvanschafflaerr@timesonline.co.uk","gender":"Male","weight":71,"dob":"2005-11-21"},
{"first_name":"Roi","last_name":"Grimsdale","email":"rgrimsdales@imgur.com","gender":"Male","weight":62,"dob":"2001-11-23"},
{"first_name":"Doloritas","last_name":"Stafford","email":"dstaffordt@imgur.com","gender":"Female","weight":39,"dob":"2002-10-31"},
{"first_name":"Maggie","last_name":"Iiannoni","email":"miiannoniu@xing.com","gender":"Female","weight":57,"dob":"2004-04-21"},
{"first_name":"Tristam","last_name":"Carleman","email":"tcarlemanv@pcworld.com","gender":"Male","weight":94,"dob":"2005-12-21"},
{"first_name":"Benjamin","last_name":"Leaf","email":"bleafw@va.gov","gender":"Male","weight":40,"dob":"2000-01-05"},
{"first_name":"Teri","last_name":"von Hagt","email":"tvonhagtx@ow.ly","gender":"Female","weight":44,"dob":"1999-07-08"},
{"first_name":"Jamil","last_name":"Cuddehay","email":"jcuddehayy@deviantart.com","gender":"Male","weight":48,"dob":"2004-11-16"},
{"first_name":"Teena","last_name":"Dounbare","email":"tdounbarez@nyu.edu","gender":"Female","weight":75,"dob":"2004-02-09"},
{"first_name":"Rozelle","last_name":"Phlippsen","email":"rphlippsen10@alexa.com","gender":"Female","weight":42,"dob":"2004-12-19"},
{"first_name":"Kennett","last_name":"Iskowicz","email":"kiskowicz11@storify.com","gender":"Male","weight":37,"dob":"2005-05-20"},
{"first_name":"Lucretia","last_name":"Mowbury","email":"lmowbury12@archive.org","gender":"Female","weight":51,"dob":"2001-10-03"},
{"first_name":"Megan","last_name":"Puddefoot","email":"mpuddefoot13@newyorker.com","gender":"Female","weight":65,"dob":"2003-12-29"},
{"first_name":"Jehanna","last_name":"Morrissey","email":"jmorrissey14@prlog.org","gender":"Female","weight":64,"dob":"2004-04-03"},
{"first_name":"Elnar","last_name":"Jowitt","email":"ejowitt15@netlog.com","gender":"Male","weight":40,"dob":"1999-12-24"},
{"first_name":"Colly","last_name":"Boniface","email":"cboniface16@facebook.com","gender":"Female","weight":80,"dob":"1999-11-01"},
{"first_name":"Bondon","last_name":"Heathwood","email":"bheathwood17@imdb.com","gender":"Male","weight":35,"dob":"1998-08-28"},
{"first_name":"Sherwin","last_name":"Hancke","email":"shancke18@bigcartel.com","gender":"Male","weight":91,"dob":"1999-12-30"},
{"first_name":"Alida","last_name":"Pyer","email":"apyer19@clickbank.net","gender":"Female","weight":64,"dob":"2003-08-31"},
{"first_name":"Anatol","last_name":"Point","email":"apoint1a@guardian.co.uk","gender":"Male","weight":43,"dob":"2001-02-01"},
{"first_name":"Royal","last_name":"Waddilow","email":"rwaddilow1b@biblegateway.com","gender":"Male","weight":51,"dob":"2003-03-16"},
{"first_name":"Kristopher","last_name":"Semiraz","email":"ksemiraz1c@vinaora.com","gender":"Male","weight":72,"dob":"2002-02-03"},
{"first_name":"Cristi","last_name":"Enrietto","email":"cenrietto1d@plala.or.jp","gender":"Female","weight":68,"dob":"1998-09-28"},
{"first_name":"Michaella","last_name":"Guitton","email":"mguitton1e@elegantthemes.com","gender":"Female","weight":76,"dob":"2002-07-12"},
{"first_name":"Brnaby","last_name":"Mobbs","email":"bmobbs1f@uiuc.edu","gender":"Male","weight":86,"dob":"2004-09-21"},
{"first_name":"Gayla","last_name":"Meininger","email":"gmeininger1g@quantcast.com","gender":"Female","weight":56,"dob":"2005-07-02"},
{"first_name":"Rhianon","last_name":"Jerdon","email":"rjerdon1h@blinklist.com","gender":"Female","weight":59,"dob":"2005-04-19"},
{"first_name":"Burlie","last_name":"Keasy","email":"bkeasy1i@1und1.de","gender":"Male","weight":37,"dob":"2002-07-03"},
{"first_name":"Alaine","last_name":"Ciobotaru","email":"aciobotaru1j@nbcnews.com","gender":"Female","weight":45,"dob":"1999-03-26"},
{"first_name":"Mozes","last_name":"Ollivierre","email":"mollivierre1k@abc.net.au","gender":"Male","weight":59,"dob":"1999-11-30"},
{"first_name":"Adah","last_name":"Burburough","email":"aburburough1l@cnet.com","gender":"Female","weight":66,"dob":"1998-10-10"},
{"first_name":"Edy","last_name":"Ingles","email":"eingles1m@a8.net","gender":"Female","weight":91,"dob":"2004-07-17"},
{"first_name":"Mag","last_name":"Obray","email":"mobray1n@fc2.com","gender":"Female","weight":61,"dob":"2005-01-04"},
{"first_name":"Vida","last_name":"Adess","email":"vadess1o@youku.com","gender":"Female","weight":44,"dob":"2004-10-12"},
{"first_name":"Donnell","last_name":"Knowler","email":"dknowler1p@dion.ne.jp","gender":"Male","weight":59,"dob":"1999-02-03"},
{"first_name":"Arvin","last_name":"Reedy","email":"areedy1q@hud.gov","gender":"Male","weight":50,"dob":"2004-11-26"},
{"first_name":"Hugues","last_name":"Baudasso","email":"hbaudasso1r@japanpost.jp","gender":"Male","weight":47,"dob":"2004-04-18"},
{"first_name":"Ignaz","last_name":"Carmo","email":"icarmo1s@cafepress.com","gender":"Male","weight":56,"dob":"2005-07-24"},
{"first_name":"Cosimo","last_name":"Dorrity","email":"cdorrity1t@simplemachines.org","gender":"Male","weight":59,"dob":"2005-04-17"},
{"first_name":"Raymond","last_name":"Daid","email":"rdaid1u@nifty.com","gender":"Male","weight":50,"dob":"2004-03-27"},
{"first_name":"Neysa","last_name":"Anney","email":"nanney1v@yellowpages.com","gender":"Female","weight":69,"dob":"2003-08-15"},
{"first_name":"Marshall","last_name":"Tumbridge","email":"mtumbridge1w@biglobe.ne.jp","gender":"Male","weight":57,"dob":"2001-07-26"},
{"first_name":"Rustie","last_name":"Pigot","email":"rpigot1x@squarespace.com","gender":"Male","weight":75,"dob":"2004-01-29"},
{"first_name":"Cecilio","last_name":"McGrane","email":"cmcgrane1y@surveymonkey.com","gender":"Male","weight":97,"dob":"2003-04-25"},
{"first_name":"Geordie","last_name":"Slatter","email":"gslatter1z@samsung.com","gender":"Male","weight":67,"dob":"2002-06-10"},
{"first_name":"Albina","last_name":"Kennler","email":"akennler20@com.com","gender":"Female","weight":67,"dob":"2001-05-24"},
{"first_name":"Batholomew","last_name":"Dmitr","email":"bdmitr21@mozilla.org","gender":"Male","weight":99,"dob":"2003-01-05"},
{"first_name":"Allsun","last_name":"Sirman","email":"asirman22@nyu.edu","gender":"Female","weight":87,"dob":"2003-01-19"},
{"first_name":"Luelle","last_name":"Rogger","email":"lrogger23@ning.com","gender":"Female","weight":87,"dob":"1999-06-01"},
{"first_name":"Guthrey","last_name":"Halwood","email":"ghalwood24@loc.gov","gender":"Male","weight":37,"dob":"2000-11-25"},
{"first_name":"Emelia","last_name":"Goodayle","email":"egoodayle25@samsung.com","gender":"Female","weight":42,"dob":"1999-05-18"},
{"first_name":"Kenna","last_name":"Buney","email":"kbuney26@digg.com","gender":"Female","weight":66,"dob":"2001-11-18"},
{"first_name":"Dietrich","last_name":"Murcutt","email":"dmurcutt27@nifty.com","gender":"Male","weight":68,"dob":"2005-01-18"},
{"first_name":"Michal","last_name":"Briand","email":"mbriand28@cnbc.com","gender":"Male","weight":94,"dob":"2004-05-19"},
{"first_name":"Bastien","last_name":"Wisher","email":"bwisher29@sun.com","gender":"Male","weight":69,"dob":"2003-12-26"},
{"first_name":"Barr","last_name":"Pietruszka","email":"bpietruszka2a@guardian.co.uk","gender":"Male","weight":63,"dob":"1999-04-26"},
{"first_name":"Granny","last_name":"Baldry","email":"gbaldry2b@loc.gov","gender":"Male","weight":73,"dob":"2005-02-12"},
{"first_name":"Tadd","last_name":"Scala","email":"tscala2c@rediff.com","gender":"Male","weight":94,"dob":"1999-02-27"},
{"first_name":"Buiron","last_name":"Bourthouloume","email":"bbourthouloume2d@princeton.edu","gender":"Male","weight":86,"dob":"1998-05-04"},
{"first_name":"Case","last_name":"Cud","email":"ccud2e@ning.com","gender":"Male","weight":42,"dob":"2004-03-23"},
{"first_name":"Jayme","last_name":"Petigrew","email":"jpetigrew2f@macromedia.com","gender":"Male","weight":75,"dob":"2000-12-03"},
{"first_name":"Brandais","last_name":"Walduck","email":"bwalduck2g@sogou.com","gender":"Female","weight":71,"dob":"1999-12-13"},
{"first_name":"Billie","last_name":"Emberton","email":"bemberton2h@bbc.co.uk","gender":"Female","weight":55,"dob":"2005-12-23"},
{"first_name":"Diane","last_name":"Behn","email":"dbehn2i@tinypic.com","gender":"Female","weight":95,"dob":"2004-10-25"},
{"first_name":"Christalle","last_name":"Dymick","email":"cdymick2j@pinterest.com","gender":"Female","weight":92,"dob":"2001-09-02"},
{"first_name":"Jason","last_name":"Haggar","email":"jhaggar2k@4shared.com","gender":"Male","weight":37,"dob":"2004-12-06"},
{"first_name":"Mei","last_name":"Pearne","email":"mpearne2l@mail.ru","gender":"Female","weight":77,"dob":"1998-12-27"},
{"first_name":"Olly","last_name":"Meadows","email":"omeadows2m@intel.com","gender":"Male","weight":74,"dob":"1998-03-05"},
{"first_name":"Natasha","last_name":"Haberfield","email":"nhaberfield2n@skyrock.com","gender":"Female","weight":44,"dob":"2003-07-22"},
{"first_name":"Katya","last_name":"Gluyas","email":"kgluyas2o@photobucket.com","gender":"Female","weight":73,"dob":"1999-04-06"},
{"first_name":"Royall","last_name":"Dexter","email":"rdexter2p@washington.edu","gender":"Male","weight":71,"dob":"2000-01-08"},
{"first_name":"Nikaniki","last_name":"Holtham","email":"nholtham2q@pcworld.com","gender":"Female","weight":44,"dob":"2004-05-18"},
{"first_name":"Sarena","last_name":"Evason","email":"sevason2r@vkontakte.ru","gender":"Female","weight":97,"dob":"2004-10-06"}]
        for c in customers:
            customer = Customer(**c)
            customer.save()
        print("Done")

# customer = Customer(**c) same as # customer_one = Customer(first_name='John', last_name='Doe',
# email='johndoe@gmail.com', dob='1996-09-17', gender='Male', weight=74)

# python manage.py populate